Show a valid error when "Base Diff Path" is missing.
Some users were trying to create review requests against subversion repositories
via the web form without specifying a base diff path.  This was showing this
error:
	'UploadDiffForm' object has no attribute 'cleaned_data'

This sucks.  This change just catches the AttributeError and raises something
more meaningful.