Fix an exception in the fill-database script.
fill-database.py raised the following error "AttributeError: 'file'
object has no attribute 'size'" whenever it was called with a greater
than 0 diff number.

Updating the script to use UploadedFile instead of a regular File object
fixes the problem.

Reviewed at http://reviews.reviewboard.org/r/3086/