Fix error dispatching webhook with auth credentials
The error was:

    AttributeError: 'SplitResult' object has no attribute 'params'

The 5-tuple used for rebuilding the URL was missing the `fragment` element instead.

Bugs closed: 4879

Reviewed at https://reviews.reviewboard.org/r/11191/